interface host-funcs {
  current-user: func() -> string
}

default world demo {
  import host: self.host-funcs

  export people: interface {
    record parent {
      name: string,
      dead: bool,
    }
    record person {
      name: string,
      age: u32,
      parent: parent,
    }

    hello: func(who: option<person>) -> person
  }
}